# Generated by Django 3.2.8 on 2021-10-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
